language: node_js
os: linux
node_js: 14
services: [docker]
install:
  - cd server && npm install
script:
  - cd docker && docker-compose -f testing.yaml up
  - cd server && npm test
after_success:
  - |
    if [ ! -z "$TRAVIS_TAG" ]; then
      cd docker && bash build.sh ${TRAVIS_TAG}
    fi