language: node_js
os: linux
node_js: 14
services: [docker]
install:
  - yarn install
script:
  - cd docker && docker-compose -f testing.yaml up -d && cd -
  - cd packages/server && yarn build && cd -
  - cd packages/web    && yarn build && cd -
  - cd packages/server && yarn test && cd -
